version: "2"
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=admin"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=influxadmin"
      - "DOCKER_INFLUXDB_INIT_ORG=system"
      - "DOCKER_INFLUXDB_INIT_BUCKET=default"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-token"

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
