version: "2"
services:

  tempo:
    image: grafana/tempo:latest
    ports:
      - 3200:3200
      - 14317:14317
    command: ["tempo", "-config.file", "/etc/tempo.conf"]
    volumes:
      - ./tempo.conf:/etc/tempo.conf

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - "GF_FEATURE_TOGGLES_ENABLE=tempoSearch"
